# Generated by Django 4.0.6 on 2022-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_jobpostactivity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='채용확인 상태')),
            ],
            options={
                'db_table': 'recruit_status',
            },
        ),
    ]
