# Generated by Django 4.0.5 on 2022-06-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_hobby_userprofile_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(to='user.hobby', verbose_name='취미'),
        ),
    ]
