# Generated by Django 4.0.5 on 2022-06-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_categories_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='product_name',
        ),
    ]
