# Generated by Django 4.0.6 on 2022-07-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_applyjobpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjobpost',
            old_name='jobpost',
            new_name='job_post',
        ),
    ]
