# Generated by Django 4.0.5 on 2022-06-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(default=0, verbose_name='등록일자'),
        ),
    ]
