# Generated by Django 4.0.5 on 2022-06-27 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 13, 47, 14, 376196), verbose_name='등록일자'),
        ),
    ]
