# Generated by Django 4.0.5 on 2022-06-27 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exposure_end_date',
            field=models.DateTimeField(default=0, verbose_name='게시 종료 일자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exposure_start_date',
            field=models.DateTimeField(default=0, verbose_name='게시 시작 일자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 13, 49, 57, 277065), verbose_name='등록일자'),
        ),
    ]
