# Generated by Django 4.0.5 on 2022-06-27 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_exposure_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 14, 59, 46, 386995), verbose_name='등록일자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='product/', verbose_name='썸네일'),
        ),
    ]
