# Generated by Django 4.0.6 on 2022-07-08 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_jobpost_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.jobpost', verbose_name='채용공고')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
            ],
            options={
                'db_table': 'enroll_status',
            },
        ),
    ]
